### ISSUE TITLE
gtsrcmaps does nothing

### ISSUE THREAD

**Issue by jballet** [fermi-lat/Likelihood#10] opened 2018-11-14 15:21 UTC
# packages in environment at /dsm/saplxglast/glast/fermitools/1.0.0:
#
# Name                    Version                   Build  Channel
fermitools                1.0.0            py27h481b005_0    fermi
fermitools-data           0.13                          0    fermi

Linux sapgaia1.extra.cea.fr 3.10.0-123.4.2.el7.x86_64 #1 SMP Tue Jun 24 13:05:26 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux

I am trying to use gtsrcmaps to generate source maps for diffuse sources in my XML file.
The same command which works well with the previous Science Tools appears to do nothing with the fermitools.
gtsrcmaps expcube=/dsm/saplxglast/glast/data/Pass8/P305/ltcube_8years_zmax80.fits cmap=srcMap_1_E1.fits srcmdl=JMC8years_zmax80_PSF3.xml bexpmap=/dsm/manip/glast/runs/P305_JMC8years/like/Rois/binned_exposure_E1.fits outfile=toto.fits irfs=CALDB chatter=4

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

This is gtsrcmaps version HEAD
ResponseFunctions::load: IRF used: P8R3_SOURCE_V2 (PSF)
  event_types:  5
difference in gti interval found

WARNING: 
AppHelpers::checkTimeCuts:
Time range cuts and GTI extensions in files srcMap_1_E1.fitsand /dsm/saplxglast/glast/data/Pass8/P305/ltcube_8years_zmax80.fits[Exposure] do not agree.
Aggregate absolute differences in GTI start times (s): 1.19209e-07
Aggregate absolute differences in GTI stop times (s): 0

Creating source named iso_P8R3_Source_v2
Creating source named gal_8yearJMC

After that the output file is the same as the input file.
ftlist toto.fits h

        Name               Type       Dimensions
        ----               ----       ----------
HDU 1   Primary Array      Image      Real4(26x26x6)                
HDU 2   GTI                BinTable     2 cols x 46969 rows         
HDU 3   EBOUNDS            BinTable     3 cols x 6 rows             

The same command with the Science Tools generates many more output lines starting with
Generating SourceMap for gal_8yearJMCMapBase::readFitsFile: creating WcsMap2 object
and creates two extensions in the output file corresponding to the two sources in my model
ftlist toto.fits h

        Name               Type       Dimensions
        ----               ----       ----------
HDU 1   Primary Array      Image      Real4(26x26x6)                
HDU 2   GTI                BinTable     2 cols x 46969 rows         
HDU 3   EBOUNDS            BinTable     3 cols x 6 rows             
HDU 4   gal_8yearJMC       Image      Real4(26x26x7)                
HDU 5   iso_P8R3_Source_v2 Image      Real4(26x26x7)                

The warning related to the small GTI difference is innocuous.
I have no idea what causes the new warning
WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
I tried simplifying my environment, to no avail.

**Comment by jasercion** [comment] 2018-12-06 19:33
Hi @jballet,

Apologies for the delayed response.  There does in fact seem to be a problem with gtsrcmaps.  We've run some testing and it seems that gtsrcmaps is no longer generating source maps for the individual sources in the input xml model, which is why the new output you posted seems to only contain an image for the entire field as opposed to including the other diffuse sources (gal_8yearJMC and iso_P8R3) as additional HDUs containing their own maps.  

@eacharles do you have an insight as to why this would have changed?

**Comment by tibaldo** [comment] 2018-12-07 13:20
I can confirm I see the same problem with the latest release
# Name                    Version                   Build  Channel
fermitools                1.0.0            py27h5b5c8cd_0    fermi
fermitools-data           0.13                          0    fermi
on My Mac OS High Sierra Laptop (Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64).
Let me stress that this is a most urgent issue, because it prevents users from running the most standard LAT analysis.

**Comment by jasercion** [comment] 2018-12-25 01:11
Hi @jballet and @tibaldo.  I have an alpha build up on our channel which should contain a fix for this problem.  Could you please install and independantly validate that this build does in fact fix the issue?  This can be done via the command

`conda install -c conda-forge -c fermi/label/alpha fermitools`

The version number you should see when running `conda list fermitools` is `1.0.3`.

Tagging @joeastro for additional verification.

**Comment by jballet** [comment] 2018-12-25 11:41
Thank you.
On my side I will not be able to test that before January 7.

________________________________
De : jasercion [notifications@github.com]
Envoyé : mardi 25 décembre 2018 02:11
À : fermi-lat/Likelihood
Cc : Ballet Jean; Mention
Objet : Re: [fermi-lat/Likelihood] gtsrcmaps does nothing (#10)


Hi @jballet<https://github.com/jballet> and @tibaldo<https://github.com/tibaldo>. I have an alpha build up on our channel which should contain a fix for this problem. Could you please install and independantly validate that this build does in fact fix the issue? This can be done via the command

conda install -c conda-forge -c fermi/label/alpha fermitools

The version number you should see when running conda list fermitools is 1.0.3.

Tagging @joeastro<https://github.com/joeastro> for additional verification.

**Comment by tibaldo** [comment] 2019-01-07 10:11
Hi @joeastro 
thanks a lot! I was also on vacation till today, but I took a first look and gtsrcmaps in the patch version behaves as expected.
I will test more and let you know if I encounter any issues.

**Comment by jasercion** [comment] 2019-02-01 18:43
Reopening issue until patch release is live.

**Comment by donhorner** [comment] 2019-03-06 19:18
Fermitools 1.0.1 was just released which should fix this.

**Closed by donhorner** 2019-03-06 19:18 UTC
