### ISSUE TITLE
Extraneous output to stdout

### ISSUE THREAD

**Issue by giacomov** [fermi-lat/Likelihood#13] opened 2018-11-28 21:30 UTC
During an Unbinned analysis the ST output a long list of lines like:

```
('srcName ', 1.1685399772994111e-05)
('srcName ', 4.0859726456770996e-05)
('srcName ', 3.3039472664381369e-05)
('srcName ', 1.9733785574060405e-05)
('srcName ', 6.4122068216531335e-05)
('srcName ', 1.9609684894508672e-05)
('srcName ', 7.7001709010895828e-06)
('srcName ', 0.00016954473425515179)
('srcName ', 5.0307662630395076e-06)
('srcName ', 0.00026842977034437985)
('srcName ', 0.00012992075268942725)
('srcName ', 0.001101561234425445)
('srcName ', 0.00012433731794941753)
('srcName ', 2.5878279434473013e-05)
('srcName ', 8.8923999448503236e-05)
('srcName ', 0.00071778624039122514)
('srcName ', 0.00060066630989645672)
('srcName ', 2.6352449575130935e-05)
('srcName ', 3.6469314251118298e-05)
('srcName ', 0.00061955634741029818)
('srcName ', 0.0010679169630160266)
('srcName ', 0.00021397394800339056)
('srcName ', 0.00050995191479426391)
('srcName ', 0.0011900747473878768)
('srcName ', 0.0010582514315924624)
('srcName ', 0.00061398717861018922)
('srcName ', 0.00010454499864707238)
('srcName ', 3.7517731528251971e-06)
('srcName ', 0.0040320556833969047)
('srcName ', 0.017271262885641216)
('srcName ', 0.00023533999447016289)
('srcName ', 0.00054560663461357536)
('srcName ', 0.00010733988638311983)
('srcName ', 4.1463496358878274e-05)
('srcName ', 0.0016526237709698075)
('srcName ', 0.00058562098814899841)
('srcName ', 0.0034071200066778098)
('srcName ', 0.00062711571987250647)
('srcName ', 0.0013974570490765572)
('srcName ', 0.00015034702705570181)
('srcName ', 8.8652459421720967e-05)
('srcName ', 0.00032038468219311705)
('srcName ', 0.0002229400071023533)
('srcName ', 7.952240674942479e-06)
('srcName ', 0.00065195328804582258)
('srcName ', 5.0250799773778252e-05)
('srcName ', 0.00064327165389847785)
('srcName ', 0.0013379637543153365)
('srcName ', 0.00017910130976088749)
('srcName ', 0.00048265715104696454)
('srcName ', 0.0032659747983683068)
('srcName ', 2.1417086866690536e-05)
('srcName ', 4.1768394770870389e-05)
('srcName ', 9.1606915349542887e-06)
('srcName ', 0.0010177466528984852)
('srcName ', 0.00024342654030137868)
('srcName ', 4.7240222791367625e-05)
('srcName ', 1.7789155524764242e-05)
('srcName ', 0.0015939760371248288)
('srcName ', 0.00024729316612258806)
('srcName ', 0.00081384178169467681)
('srcName ', 0.0003129510491094414)
('srcName ', 0.001415038590322206)
('srcName ', 0.00018986306191508812)
('srcName ', 0.0)
('srcName ', 0.00089015581624073939)
('srcName ', 0.0068218269090124135)
('srcName ', 0.00039907283882629639)
('srcName ', 0.00054365189558182152)
('srcName ', 0.0001947546745844354)
('srcName ', 0.0013468063603294036)
('srcName ', 1.0470663577684908e-05)
('srcName ', 0.0031082880150112022)
('srcName ', 0.0)
('srcName ', 0.00034598358350086141)
('srcName ', 0.0016160736398935043)
('srcName ', 4.5141902058564272e-05)
('srcName ', 0.0012222655958550801)
('srcName ', 0.00019254725992280883)
('srcName ', 8.1229689626100872e-05)
('srcName ', 0.00044336558865448121)
('srcName ', 0.0)
('srcName ', 0.00024304915699484294)
('srcName ', 0.00092532698993049681)
('srcName ', 0.0036972385266802366)
('srcName ', 0.001002523776250853)
('srcName ', 0.00096347961952634466)
('srcName ', 0.0015292464922588417)
('srcName ', 0.0)
('srcName ', 0.00063462583470753106)
('srcName ', 0.00024624234381575574)
('srcName ', 4.9837152826714233e-05)
('srcName ', 0.00015975092801602617)
('srcName ', 0.0)
('srcName ', 5.2625374665504457e-05)
('srcName ', 0.0)
('srcName ', 6.8068567478808396e-05)
('srcName ', 9.9830259123265811e-05)
('srcName ', 0.00087707953018620615)
('srcName ', 0.00082205775617063951)
('srcName ', 0.0)
('srcName ', 0.00051757832516123939)
('srcName ', 0.0001611397857359279)
('srcName ', 5.4884006431790489e-05)
('srcName ', 0.00023733683404158126)
('srcName ', 0.00017152494320809265)
('srcName ', 3.9604416740205179e-05)
('srcName ', 0.0009747389684117765)
('srcName ', 5.4032900533898652e-05)
('srcName ', 0.00019988672590250082)
('srcName ', 2.5088355599444975e-05)
('srcName ', 0.000736041080220538)
('srcName ', 0.00015538569742002819)
('srcName ', 0.00051684689182368408)
('srcName ', 7.6947027996349319e-05)
('srcName ', 0.0)
('srcName ', 1.5636540759515516e-05)
('srcName ', 0.001639664095441777)
('srcName ', 0.00018990349961627709)
('srcName ', 2.8075913011437061e-05)
('srcName ', 0.0)
('srcName ', 1.2586310194685968e-05)
('srcName ', 0.0)
('srcName ', 0.00013622228882154299)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 3.7285230905511189e-05)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 0.00011491686466152057)
('srcName ', 2.1932601502458715e-05)
('srcName ', 0.0)
('srcName ', 2.8121516001465576e-05)
('srcName ', 1.7752189799081115e-06)
('srcName ', 4.2825429354175102e-05)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 0.0)
('srcName ', 8.1221178217066864e-05)
('srcName ', 1.5882845669165511e-05)
('srcName ', 5.3489254346550263e-07)
('srcName ', 0.0)
('srcName ', 2.7184726037645738e-05)
('srcName ', 0.89968773262379809)
('srcName ', 1.016960354602036)
('srcName ', 2.9051403423672473)
('Resid ', 5.0, 4.9088854799435966, -9.0429444910865318)
```

It is probably some debug code that was left by mistake.

**Comment by donhorner** [comment] 2019-03-15 18:39
@dagorym This looks like it should be a quick and simple fix.  Can you take a look?

**Comment by dagorym** [comment] 2019-03-15 21:54
I can't actually reproduce this.  I've run all the science tools in the Binned Likelihood thread except gtselect and don't see this output anywhere.  So it looks like in the current release, whatever was producing this output has been turned off.  Or it's in the unbinned code.  I'll try that next.

**Comment by dagorym** [comment] 2019-03-18 22:11
Okay, I've tried this with the unbinned thread as well and can't seem to reproduce the problem.  I'm going to close it as non-reproducible.  Maybe whatever updates we had in the last release turned the output off.  If it shows up again, we need sample files to try that produce the problem as well as which version it was occurring in.

**Closed by dagorym** 2019-03-18 22:11 UTC
